services:
  app-prod:
    image: next-blog-app-prod
    container_name: next-blog-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail http://localhost:3000/api/health
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db-prod:5432/${DB_NAME}

  db-prod:
    image: postgres:16
    container_name: next-blog-db-prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data_prod:
